### ISSUE TITLE
Aim pp seems to be broken

### ISSUE THREAD

**Issue by j1nxie** [srb2thepast/osu-alltrick#7]
As stated on title, aim pp seems to be very broken, with values jumping to the thousands (!). Screenshot attached below.

![image](https://user-images.githubusercontent.com/52886388/204477679-5182ee5e-dd60-4a42-8a7a-469b27ccd4b3.png)

**Comment by srb2thepast** [comment]
Right, currently the calculator used for aim pp is simply outputting a completely random number from 0-120k. All of the scores' aim pp will be recalculated once a proper calculator is created, but for now it's a little joke.

Will close as this issue as completed once aim gets a proper calculator.
